"""
MDP Interface for: {task_description}
Generated by evolutionary iteration {iteration_number}

Environment: xland-minigrid
All code must be JAX-compatible. Use jnp (not np). Use jax.lax for control flow
on traced values (no Python if/else on JAX arrays).

== State fields available ==

  state.grid             jax.Array (H, W, 2)  — grid[r, c, 0] is tile_id, grid[r, c, 1] is color_id
  state.agent.position   jax.Array (2,)       — [row, col]
  state.agent.direction  jax.Array scalar     — 0=Up, 1=Right, 2=Down, 3=Left
  state.agent.pocket     jax.Array (2,)       — [tile_id, color_id] of held item (EMPTY=0 if nothing)
  state.goal_encoding    jax.Array (5,)       — encoded goal specification
  state.rule_encoding    jax.Array (N, 7)     — encoded rules
  state.step_num         jax.Array scalar     — current timestep (uint8)

== Tile constants ==

  EMPTY=0  FLOOR=1  WALL=2  BALL=3  SQUARE=4  PYRAMID=5  GOAL=6
  KEY=7  DOOR_LOCKED=8  DOOR_CLOSED=9  DOOR_OPEN=10  HEX=11  STAR=12

== Color constants ==

  EMPTY=0  RED=1  GREEN=2  BLUE=3  PURPLE=4  YELLOW=5
  GREY=6  BLACK=7  ORANGE=8  WHITE=9  BROWN=10  PINK=11

== Direction constants ==

  UP=0  RIGHT=1  DOWN=2  LEFT=3

== Action constants ==

  FORWARD=0  TURN_RIGHT=1  TURN_LEFT=2  PICKUP=3  PUTDOWN=4  TOGGLE=5

== Constraints ==

  - get_observation must return a 1D jnp.float32 array (max 512 elements).
  - compute_reward must return a scalar jnp.float32 value.
  - All code must be JAX-traceable (no Python if/else on jax arrays, use jax.lax.cond/select).
  - Only use jax, jax.numpy (as jnp), jax.lax. No other imports.
"""

import jax
import jax.numpy as jnp


def get_observation(state) -> jnp.ndarray:
    """Extract and transform observations from the raw environment state.

    The RL agent sees ONLY what this function returns.
    You decide what information to include, exclude, transform, or combine.

    Args:
        state: xminigrid State object (see field reference above).

    Returns:
        1D jnp.float32 array — the observation vector for the policy network.
    """
    flat_grid = state.grid.reshape(-1).astype(jnp.float32)
    pos = state.agent.position.astype(jnp.float32)
    direction = jax.nn.one_hot(state.agent.direction, 4)
    pocket = state.agent.pocket.astype(jnp.float32)
    step = jnp.array([state.step_num.astype(jnp.float32)])
    obs = jnp.concatenate([flat_grid, pos, direction, pocket, step])
    return obs


def compute_reward(state, action, next_state) -> jnp.ndarray:
    """Compute the reward signal for the RL agent.

    This is the ONLY reward the agent receives during training.
    Design this to induce the desired behavior described in the task.

    Args:
        state: Environment state before the action.
        action: Integer action that was taken (0-5).
        next_state: Environment state after the action.

    Returns:
        Scalar jnp.float32 reward value.
    """
    reward = jnp.float32(-0.01)
    return reward
