"""
MDP Interface for: {task_description}
Generated by evolutionary iteration {iteration_number}

All code must be JAX-compatible. Use jnp (not np). Use jax.lax for control flow
on traced values (no Python if/else on JAX arrays).

Refer to the library reference (context document) for available state fields,
constants, and patterns.

== Constraints ==

  - get_observation must return a 1D jnp.float32 array (max 512 elements).
  - compute_reward must return a scalar jnp.float32 value.
  - All code must be JAX-traceable (no Python if/else on jax arrays, use jax.lax.cond/select).
  - Only use jax, jax.numpy (as jnp), jax.lax. No other imports.
"""

import jax
import jax.numpy as jnp


def get_observation(state) -> jnp.ndarray:
    """Extract and transform observations from the raw environment state.

    The RL agent sees ONLY what this function returns.
    You decide what information to include, exclude, transform, or combine.

    Args:
        state: Environment state object (see library reference for available fields).

    Returns:
        1D jnp.float32 array — the observation vector for the policy network.
    """
    # Example: flatten all state features into a single vector
    # Replace this with a task-appropriate observation design
    flat_grid = state.grid.reshape(-1).astype(jnp.float32)
    pos = state.agent.position.astype(jnp.float32)
    direction = jax.nn.one_hot(state.agent.direction, 4)
    pocket = state.agent.pocket.astype(jnp.float32)
    step = jnp.array([state.step_num.astype(jnp.float32)])
    obs = jnp.concatenate([flat_grid, pos, direction, pocket, step])
    return obs


def compute_reward(state, action, next_state) -> jnp.ndarray:
    """Compute the reward signal for the RL agent.

    This is the ONLY reward the agent receives during training.
    Design this to induce the desired behavior described in the task.

    Args:
        state: Environment state before the action.
        action: Integer action that was taken.
        next_state: Environment state after the action.

    Returns:
        Scalar jnp.float32 reward value.
    """
    reward = jnp.float32(-0.01)
    return reward
